apiVersion: v1
kind: Service           # 簡稱 svc 啦!!!!
metadata:
  name: my-nginx
  labels:
    run: my-nginxQQ
  annotations:
      service.beta.kubernetes.io/load-balancer-source-ranges: "10.140.0.0/24" # 用來限定 service 的 ip-ranges
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:            # selector 用來選擇 哪些 pods 要被綁在同一個 service裡
    app: nginx
  type: "NodePort"   # 通常是 LoadBalancer
