let En_2_Zh_Dict = {
    "social_media": "社群",
    "forum": "論壇",
    "blog": "部落格",
    "news": "新聞",
    "appledaily": "蘋果日報",
    "ck101": "卡提諾論壇",
    "dcard": "Dcard",
    "babyhome":"BabyHome 寶貝家庭親子網",
    "ettoday": '東森新聞雲',
    "eyny": "伊莉討論區",
    "facebook": 'FACEBOOK',
    "pixnet": '痞客幫',
    "ptt": "PTT",
    "setn": '三立新聞網',
    "thenewslens" : "關鍵評論網",
    "udn" : "聯合新聞網",
    "udn_money":"聯合財經網",
    "babyhome_info": "寶貝家庭親子網",
    "ithome":"iThome",
    "nownews":"今日新聞網",
    "ltn":"自由時報",
    "yam_news" : "蕃薯藤新聞網",
    "cnyes" : "鉅亨網",
    "cna":"中央通訊社",
    "chinatimes":"中國時報",
    "mobile01": "Mobile01",
    "xuite": "隨意窩",
    "cw_mag": "天下雜誌",
    "gamme_news" : "宅宅新聞網",
    "kairos" : "風向新聞網",
    "kingautos" : "國王車訊",
    "Total": "總和",
    "others":"其他",
    "--": "--"
};

let Zh_2_En_Dict = {
    "社群": "social_media",
    "論壇": "forum",
    "部落格": "blog",
    "新聞": "news",
    "蘋果日報": "appledaily",
    "卡提諾論壇": "ck101",
    "Dcard": "dcard",
    "BabyHome 寶貝家庭親子網":"babyhome",
    '東森新聞雲': "ettoday",
    "伊莉討論區": "eyny",
    'FACEBOOK': "facebook",
    '痞客幫': "pixnet",
    "PTT": "ptt",
    '三立新聞網': "setn",
    "Mobile01": "mobile01",
    "隨意窩": "xuite",
    "天下雜誌": "cw_mag",
    "關鍵評論網":"thenewslens",
    "聯合新聞網":"udn",
    "聯合財經網":"udn_money",
    "寶貝家庭親子網":"babyhome_info",
    "iThome":"ithome",
    "今日新聞網":"nownews",
    "自由時報":"ltn",
    "蕃薯藤新聞網":"yam_news",
    "鉅亨網":"cnyes",
    "中央通訊社":"cna",
    "中國時報":"chinatimes",
    "宅宅新聞網":"gamme_news",
    "風向新聞網":"kairos",
    "國王車訊":"kingautos",
    "總和": "Total",
    "其他": "others",
};

let sources_ZH_Dict = {
    "社群": ["Facebook"],
    "論壇": ["Ptt", "Mobile01", "伊莉討論區", "Dcard", "卡提諾論壇","BabyHome 寶貝家庭親子網"],
    "部落格": ["痞客幫", "隨意窩"],
    "新聞": [
        "蘋果日報", "東森新聞雲", "三立新聞網","天下雜誌","關鍵評論網",
        "聯合新聞網", "聯合財經網","寶貝家庭親子網","iThome","今日新聞網",
        "自由時報", "蕃薯藤新聞網", "鉅亨網", "中央通訊社", "中國時報",
        "宅宅新聞網","風向新聞網","國王車訊"
    ]
};

let sources_EN_Dict = {
    "social_media": ["facebook"],
    "forum": ["ptt", "mobile01", "eyny", "dcard", "ck101","babyhome"],
    "blog": ["pixnet", "xuite"],
    "news": [
        "appledaily", "ettoday", "setn","cw_mag","thenewslens",
        "udn","udn_money","babyhome_info","ithome",
        "nownews","ltn","yam_news","cnyes",
        "cna","chinatimes","gamme_news","kairos","kingautos"
    ]
};

let officialAuthorList = [
    'appledaily','ettoday','setn',"cw_mag",'Appledaily','Ettoday', "udn" , "udn_money" , "thenewslens",
    "babyhome_info","ithome","nownews","ltn","yam_news","cnyes","cna","chinatimes","柯文哲",
    '中華電信客服Q博士','中華電信行動學園','台灣大哥大與你生活在一起','遠傳電信','台灣之星',"詹晉鑒",
    '台灣之星對你最好','亞太電信 Gt 4G','中華電信行動學園','寶衛地球 讓愛遠傳',"Pubgame《遊戲酒吧》",
    '中華電信HiNet光世代','蘋果日報即時新聞','台灣大哥大基金會','東森新聞','蘋果日報','中華電信如意卡','ETtoday新聞雲',
    "爆料公社","三立娛樂星聞","Kairos 風向新聞","食尚玩家","數位時代","台灣醒報國際現場","Lucy 路雨希 2.0","Selfpick",
];

let pttCategoryDict = {
    "Gossiping":"八卦板",
    "C_Chat":"聊天板" ,
    "Baseball":"棒球板" ,
    "WomenTalk":"女性版",
    "LoL":"LOL板",
    "HatePolitics":"政黑板",
    "BabyMother": "媽寶版",
    "Japan_Travel":"日旅板",
    "MobileComm":"手機板",
    "movie":"電影版",
    "joke":"JOKE板",
    "car":"汽車板",
    "Elephants":"中信兄弟板",
    "NBA":"NBA板"  ,
    "PC_Shopping":"電蝦板" ,
    "iPhone":"iPhone板",
    "Boy-Girl":"男女板",
    "sex":"西斯板",
    "Stock":"股票板",
    "MakeUp":"美妝板",
    "Tech_Job":"科技板",
    "WOW":"WOW板",
    "StupidClown":"笨 板",
    "PokeMon":"寶可夢板",
    "KanColle":"艦娘板",
    "Beauty":"表特板",
    "Hearthstone":"爐石板",
    "IA":"國際事物板",
    "KoreaDrama":"韓劇板",
    "PuzzleDragon":"龍族拼圖板",
    "marvel":"鬼故事板",
    "marriage":"婚姻板",
    "TaiwanDrama":"臺劇板",
    "EAseries":"歐美影集板",
    "Japandrama":"日劇板",
    "Android":"Android板",
    "CrossStrait":"兩岸板",
    "PublicIssue":"公民覺醒板",
    "Digitalhome":"數位家庭板",
    "Olympics_ISG":"奧運板",
    "WindowsPhone":"Windows Phone 板",
    "Sony-style":"SONY板",
    "politics":"政治板",
    "Employee":"勞工板",
    "Salary":"職場板",
    "BeautySalon":"美保板",
    "Teacher":"教師板",
    "toberich":"創業老闆板",
    "hairdo":"美髮板",
    "guitar":"吉他板",
    "PublicServan":"公務人員板",
    "Soft_Job" : "軟體板",
    "soho" : "SOHO板",
    "Nurse": "護理師板",
    "WorkinChina" : "大陸求職板",
    "Option":"期貨選擇權板",
    "Finance":"金融業板",
    "Broker":"證券板",
    "Pedal":"器材板",
    "Gov_owned":"國營事業板",
    "Aromatherapy":"芳香療法板",
    "TaiwanJobs":"台灣就業板",
    "Oversea_Job":"海外工作板",
    "Mechanical":"機械板",
    "piano":"鋼琴板",
    "Civil":"土木板",
    "Bioindustry":"生技產業板",
    "SW_Job":"社工板",
    "bass":"BASS板",
    "CareerLady":"職場女性版",
    "unemployed":"待業板",
    "pharmacist":"藥師板",
    "Lawyer":"律師板",
    "Salesperson":"業務板",
    "Marketing":"行銷板",
    "intltrade":"國貿板",
    "DirectSales":"傳直銷板",
    "CS_TEACHER":"補教老師板",
    "MIS":"MIS板",
    "Therapist": "治療師板",
    "gardener": "幼教板",
    "tutor": "家教板",
    "HRM": "人資板",
    "DigiCurrency": "數位貨幣與電子支付板",
    "ServiceInfo": "服務業板",
    "ukulele": "烏克麗麗板",
    "Media-work": "傳播媒體人板",
    "Violin": "提琴家族板",
    "Drum": "鼓板",
    "Instrument": "樂器板",
    "medache": "醫療人員板",
    "teaching": "教材板",
    "Tour-Manager": "導遊領隊板",
    "keyboard": "鍵盤樂器板",
    "FiremanLife":"消防板",
    "Model-Agency":"模特經紀板",
    "Dietician":"營養師板",
    "Flute":"長笛板",
    "petwork":"寵物工作者板",
    "Optometrist":"驗光人員板",
    "CMstudents":"中醫學生板",
    "GuZheng":"古箏板",
    "trumpet": "小號板",
    "Property_M": "物業管理板",
    "Orchestra": "管弦樂板",
    "Horn": "法國號板",
    "Taipei"     :"台北板",
    "Neihu"      :"內湖板",
    "Wen-Shan"   :"文山板",
    "BigShiLin"  :"士林板",
    "BigPeitou"  :"北投板",
    "Daan"       :"大安板",
    "SongShan"   :"松山板",
    "Zhongshan"  :"中山板",
    "HsinYi"     :"信義板",
    "Nangang"    :"南港板",
    "Datong"     :"大同板",
    "Wanhua"     :"萬華板",
    "Zhongzheng" :"中正版",
};
module.exports = {
    En_2_Zh_Dict,
    Zh_2_En_Dict,
    sources_ZH_Dict,
    sources_EN_Dict,
    officialAuthorList,
    pttCategoryDict
};
