apiVersion: v1
kind: Service
metadata:
    name: redis-svc
    labels:
        component: redis
spec:
    selector:
        component: redis
    ports:
    -   name: http
        port: 6379
        targetPort: 6379
        protocol: TCP
