apiVersion: v1
kind: Service
metadata:
    name: eyesocial-main-webserver-svc
    labels:
        component: nodejs
        role: eyes-main-web
spec:
    type: LoadBalancer
    # loadBalancerIP: "104.199.155.102"
    selector:
        component: nodejs
        role: eyes-main-web
    ports:
    -   name: http
        port: 80
        targetPort: 32767
        protocol: TCP
