apiVersion: v1
kind: Service
metadata:
    name: eyesocial-proxy-server-svc
    labels:
        component: nodejs
        role: eyes-proxy
spec:
    type: LoadBalancer
    # loadBalancerIP: "104.199.155.102"
    selector:
        component: nodejs
        role: eyes-proxy
    ports:
    -   name: http
        port: 32980
        targetPort: 32980
        protocol: TCP
