apiVersion: v1
kind: PersistentVolume
metadata: pv_0001
spec:
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 
        path:
